name: Pipeline CI/CD

permissions:
  contents: read
  checks: write
  pull-requests: write

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('/pyproject.toml', '/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Instalar dependências (lint)
        run: pip install -e ".[test]"

      - name: Procurar erros de estilo
        run: pflake8

      - name: Checar estilo de importação (isort)
        run: isort --check --diff dundie tests integration 

      - name: Verificar formatação automática (black --check)
        run: black --check --diff dundie tests integration

  tests:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('/pyproject.toml', '/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Instalar projeto e dependências
        run: pip install -e ".[test]"

      - name: Executar testes
        run: pytest -v --junitxml=test-result-${{ matrix.python-version }}.xml

      - name: Publicar resultados dos testes (ação)
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: test-result-${{ matrix.python-version }}.xml
          check_name: Resultado dos Testes (Python ${{ matrix.python-version }})
      - name: Fazer upload do relatório de testes
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-${{ matrix.python-version }}
          path: test-result-${{ matrix.python-version }}.xml
